mods.gregtech.chemical_reactor.recipeBuilder()
    .fluidInputs(fluid('neutronium') * 50)
    .fluidInputs(fluid('stone') * 72)
    .outputs(item('gregternal:cosmic_brick'))
    .duration(200)
    .EUt(98304)
    .buildAndRegister()