//Add ore dictionary
//oredict.add("craftingTableWood", item('minecraft:crafting_table'))
//oredict.add("craftingTableWood", item('tconstruct:tooltables:0'))
//oredict.add("craftingTableWood", metaitem('gregtech:workbench'))
//oredict.add("cobblestone", item('gregtech:stone_cobble:1'))
//oredict.add("cobblestone", item('gregtech:stone_cobble:2'))
//oredict.add("cobblestone", item('gregtech:stone_cobble:3'))
//oredict.add("cobblestone", item('gregtech:stone_cobble:4'))
//oredict.add("cobblestone", item('gregtech:stone_cobble:5'))

oredict.add("bigBackpack", item('backpack:backpack:200'))
oredict.add("bigBackpack", item('backpack:backpack:201'))
oredict.add("bigBackpack", item('backpack:backpack:202'))
oredict.add("bigBackpack", item('backpack:backpack:203'))
oredict.add("bigBackpack", item('backpack:backpack:204'))
oredict.add("bigBackpack", item('backpack:backpack:205'))
oredict.add("bigBackpack", item('backpack:backpack:206'))
oredict.add("bigBackpack", item('backpack:backpack:207'))
oredict.add("bigBackpack", item('backpack:backpack:208'))
oredict.add("bigBackpack", item('backpack:backpack:209'))
oredict.add("bigBackpack", item('backpack:backpack:210'))
oredict.add("bigBackpack", item('backpack:backpack:211'))
oredict.add("bigBackpack", item('backpack:backpack:212'))
oredict.add("bigBackpack", item('backpack:backpack:213'))
oredict.add("bigBackpack", item('backpack:backpack:214'))
oredict.add("bigBackpack", item('backpack:backpack:215'))
oredict.add("bigBackpack", item('backpack:backpack:216'))